TM1py.py

Gets thread information from TM1 and returns it as a dictionary.

Get Thread Information from TM1 Server

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py

Hello!
First, thank you for the really useful TM1py project!
I wanted to pull data in a different format than what your normal execute_mdx gives so I added a couple of additional formats.  I am driving multiple synched Dygraphs from a single query with these new methods. I added a get_data method that works like execute_mdx, but could also be used as a template for a similar get_data_from_view, allowing data to be returned in any format. The get_data could be used as a drop-in replacement for execute_mdx since the additional arguments are optional and default is how execute_mdx works. (If you want to do this, I can change the order of the arguments so calls with positional arguments will still work).
Let me know what you think. I can give you some sample code so you can see the different …

Alternate formats for extracting data from MDX query

---

TM1py/Objects/Process.py
TM1py/Services/CellService.py
TM1py/Services/ProcessService.py
TM1py/Services/RESTService.py
TM1py/Utils/Utils.py
Tests/Cell.py
Tests/Process.py
Tests/Server.py

- breakdown get_data funcion into small execute_mdx methods in CellService
- Tests for new execute_mdx methods
- Prettify execute_process function. Now takes **kwargs arguments
(dynamic arguments with same name as the TI Parameters). Rename of name_process argument to process_name.
- Adapt Tests for ProcessService
- oursource cellset deletion into higher order function: tidy_cellset
- Creation of execute_view_* functions
- Rename build_dygraph_arrays_from_cellset to
build_ui_dygraph_arrays_from_cellset and build_arrays_from_cellset to build_ui_arrays_from_cellset

Refactoring get_data function

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py

Hello,
This fixes the build_content_from_cellset when aggregate queries are used. I see now the difference between member and elements. I mainly wanted Attributes and I see that they are available on Members so I refactored the code a bit assuming that member_properties will be mostly used. Elem_properties can still be used and will be included in the result set, but it does not try to flatten the properties between elements and members anymore. Also, I allow elem_properties to be None meaning we do not even want to query them. I only force the member Name property with dygraphs and arrays.
I did a quick refactor on the execute_mdx and build_content_from_cellset to remove the need to pass cell_properties to the build_content_from_cellset function; all properties included in the query will …

Fix build headers for aggregate queries

---

TM1py/Exceptions/Exceptions.py
TM1py/Objects/User.py
TM1py/Services/RESTService.py
Tests/Other.py

Now retry Authentication in RestService with b64decoded password, if authentication with plain password fails.
https://github.com/cubewise-code/TM1py/issues/62

Retry Authentication with b64 decoded password

---

TM1py/Objects/NativeView.py
TM1py/Services/ViewService.py
Tests/View.py

new get method in ViewService returns MDX or NativeView:
```
with TM1Service(address='10.77.19.60', port=12354, user='admin', password='apple', ssl=True) as tm1:
view = tm1.cubes.views.get(
cube_name="Project Planning",
view_name="I am a MDX View",
private=False)
view = tm1.cubes.views.get(
cube_name="Project Planning",
view_name="I am a Native View",
private=False)
```
solves #77

#77 add dynamic get method to ViewService

---

TM1py/Services/DimensionService.py

'Leaves' Hierarchy doesn't need to be updated or created during dimension-updates.

not-update-leaves-hierarchy-in-dimension-update

---

TM1py/Services/CellService.py
TM1py/Services/ProcessService.py
Tests/Cell.py

- Now also works for 1 x 1 cellset
- Now called `execute_mdx_rows_and_values`
- New boolean argument `element_unique_names` to control if keys in returned map are simple member names or member unique names.

Fix bug in execute_mdx_rows_and_cells method and rename it

---

TM1py/Services/CubeService.py
Tests/Cube.py

New methods in CubeService:
- `get_storage_dimension_order(self, cube_name)`
- `update_storage_dimension_order(self, cube_name, dimension_names)`
Fixes #81 
Sample:
``` python
import configparser
config = configparser.ConfigParser()
config.read(r'config.ini')
with TM1Service(**config['tm1srv01']) as tm1:
dimensions = tm1.cubes.get_storage_dimension_order("c1")
print(dimensions)
tm1.cubes.update_storage_dimension_order("c1", reversed(dimensions))
dimensions = tm1.cubes.get_storage_dimension_order("c1")
print(dimensions)
```

New get and update methods for dimension storage order

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py
Tests/Cell.py
Tests/Utils.py

- New method in `CellService`: `relative_proportional_spread`
- New utility function to parse dimension, hierarchy, element from
unique-element-name: `dimension_hierarchy_element_tuple_from_unique_name`
Fixes #108 
Sample:
``` python
import configparser
config = configparser.ConfigParser()
config.read(r'config.ini')
with TM1Service(**config['tm1srv01']) as tm1:
tm1.cubes.cells.relative_proportional_spread(
value=12,
cube="c1",
unique_element_names=("[d1].[c1]", "[d2].[e3]"),
reference_cube="c1",
reference_unique_element_names=("[d1].[c1]", "[d2].[c1]"))
```

Support relative proportional spread

---

TM1py/Services/RESTService.py

If verification is desired, pass path to .cer file when instantiating `TM1Service`
If verification shall be skipped pass `False `or `'False'`

Simplify ssl

---

TM1py/Services/RESTService.py
Tests/config.ini
setup.py

- Fail-safe import of (windows-only) dependecy `requests_negotiate_sspi`
- Optional dependency to `requests_negotiate_sspi `in `setup.py` only in
windows os
Fixes #127

Enable platform independency

---

TM1py/Services/RESTService.py

Update the RESTService to leverage the service's verify settings when issuing the CAM negotiation request. This allows the verify setting to be standardized for each individual connection and makes working through the SSL challenges easier

Updated RESTService to leverage the classes verify setting

---

TM1py/Objects/User.py
TM1py/Services/CellService.py

- If no dimension names are passed to write_values methods
TM1py will derive right dimensions (excluding Sandboxes dimension)
- Write_value and write_values methods can now write to cubes
with a sandbox dimension
- Fix compatability issue for TM1 11.5 in JSON creation of User class
Fixes #136

Fix write_value, write_values method issue

---

TM1py/Objects/Subset.py
TM1py/Objects/User.py
TM1py/Services/CellService.py
TM1py/Services/CubeService.py
TM1py/Services/ElementService.py
TM1py/Services/ObjectService.py
TM1py/Services/RESTService.py
TM1py/Services/SecurityService.py
TM1py/Utils/Utils.py
TM1py/Utils/__init__.py
Tests/Cell.py
Tests/Security.py

- new method to escape ' in object names in odata reference
- centralized call in httpmethod for escaping of ' in object names
- minor reformating and test enhancements
Fixes #145

Properly escape ' in object names in url

---

TM1py/Services/CellService.py
Tests/Cell.py

now type of `Value` column in resulting dataframe from
`execute_mdx_dataframe`, `execute_view_dataframe` is derived
from data, unless specified otherwise through `dtype` argument.
Fixes backwards compatability issue that was introduced with MR #144

Undo silent type conversion in values column

---

TM1py/Exceptions/Exceptions.py
TM1py/Services/RESTService.py

Expanded TM1Py  Exception to include the returned headers. Returning the headers allow for easier trouble shooting and auto-detection of the CAM Gateway. This will allow for easier roll out to users using SSO. 
` try:
response = TM1Service(**kwargs)
except TM1pyException as e:
response_headers = e.headers
authenticate_header = response_headers.get("WWW-Authenticate", "No Gateway Found")
if authenticate_header is not "No Gateway Found":
gateway = authenticate_header.split("CAMPassport")[1].strip().split(",")[0]
return gateway
else:
raise authenticate_header`

Expand exception detail

---

TM1py/Services/RESTService.py

in TM1Service constructor. So one does not need
to pass `None` for these arguments when using TM1py with SSO.

Accept empty values for user and password

---

TM1py/Services/ApplicationService.py

Hi Marius and Tomasz,
I found out that the new functions (get, delete, create, exists) don't handle properly the **root** folder under the Application tree (since this case the path is empty).
I've modified the functions and tested the functionality.
Cheers,
Adam

Fixed ApplicationService request URL in case of empty path (root folder)

---

TM1py/Utils/Utils.py

Hi Marius,
I've changed the way how the escaping works.
It first recognizes the object names inside the brackets and quotes then doubles the quotes afterwards.
@tombrzy will do some more testing, and we will let you know the results.
Cheers,
Adam

Restrict URL escaping to object names only

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py
Tests/Utils.py

1. A new method in `CellService`: `relative_proportional_spread`
**Sample:**
```
import configparser
config = configparser.ConfigParser()
config.read(r'config.ini')
with TM1Service(**config['tm1srv01']) as tm1:
tm1.cubes.cells.relative_proportional_spread(
cube="c1",
unique_element_names=("[d1].[c1]", "[d2].[e3]"))
```
2. Updated the `Utils` module to fix https://github.com/cubewise-code/tm1py/issues/202#issue-543913984 . Replaced the `re` pattern in line **14**

Added 'clear' data spread method

---

TM1py/Services/CellService.py
TM1py/Services/RESTService.py
Tests/Cell.py

- `http_method` decorator now supports custom encoding (e.g. `'latin-1'`). Default value is `'utf-8'`
- common read and write methods in `CellService` accept `encoding` argument through `**kwargs` and pass it down to the http call

Allow custom string encoding for cell data requests

---

TM1py/Services/RESTService.py

Configparser returns values as string by default, so using timeout in server configuration in the config file will throw an type error in urllib3, with timeout being neither int or float, like this:
File "site-packages\urllib3\util\timeout.py", line 140, in _validate_timeout
TypeError: '<=' not supported between instances of 'str' and 'int'

Cast the timeout dict value to int

---

TM1py/Objects/Hierarchy.py
TM1py/Services/DimensionService.py
TM1py/Services/HierarchyService.py

build dimension, hierarchies, elements, edges with one call.
Then create ElementeAttributes in a seperate call without updating Elements, Edges.

Fix redundant calls in dimension update and create

---

TM1py/Objects/Process.py
TM1py/Services/ChoreService.py
TM1py/Services/DimensionService.py
TM1py/Services/RestService.py
Tests/RestService.py
setup.py

When TM1 is hosted in the IBM cloud, there is a hard constraint that incoming REST requests time out after 60 seconds. 
So far the only way to work around this constraint with TM1py was to avoid executing large queries and long-running processes.
This issue is now addressed.
When instantiating the `TM1Service` (or any other TM1py Service), you can pass `async_requests_mode=True`  as an optional argument.
The user would not notice the difference when dealing with a high-level TM1py Service.
Behind the scenes, TM1py will execute all requests in an async-mode. That means in the `RestService` we do a request and then check in fixed intervals (0.1s, 0.3s, 0.6s, 1s, 1s, 1s. ... ) if the response is available, until the TM1py timeout is reached (if a TM1py timeout is configured)
Fixes …

Introduce `ibm_cloud_mode` to Tm1Service

---

TM1py/Utils/Utils.py

Instead of getting the list via dict(orient), getting it via numpy improves the efficiency by 50%.
df.shape = (106920, 12)
new method took - 0.9022 seconds
old method took - 1.7175 seconds

Improving build_cellset_from_pandas_dataframe method

---

TM1py/Utils/Utils.py
Tests/Utils.py

REST API returned duration like this {'ElapsedTime': 'P0DT00H02M16S', 'WaitTime': 'P0DT00H00M00S'} can be converted to seconds (136).
```
import pandas as pd
import re
def get_seconds_from_duration(time_str: str) -> int:
"""
This function will convert the TM1 time to seconds
:param time_str: P0DT00H01M43S
:return: int
"""
pattern = re.compile('\w(\d+)\w\w(\d+)\w(\d+)\w(\d+)\w')
matches = pattern.search(time_str)
d, h, m, s = matches.groups()
seconds = (int(d) * 86400) + (int(h) * 3600) + (int(m) * 60) + int(s)
return seconds
with TM1Service(address=ADDRESS, port=PORT, ssl=SSL, user=USER, password=PASSWORD) as tm1:
threads = pd.DataFrame(tm1.monitoring.get_threads())
threads[['ElapsedTime', 'WaitTime']] = threads[['ElapsedTime', …
```

Method to convert the Duration to seconds

---

TM1py/Services/ElementService.py
Tests/Element.py

I would use it something like this:
```
with TM1Service(address=ADDRESS, port=PORT, ssl=SSL, user=USER, password=PASSWORD) as tm1:
period = tm1.elements.get_element_by_attribute(dimension_name='Period', hierarchy_name='Period', 
attribute='Month', elements=['01', '02'], 
exclude_empty_cells=True, element_unique_names=False)
```
the output would be:
`{'01': 'Jan', '02': 'Feb'}`

New method for getting element(')s respective attribute values

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py

1. Correcting typing mismatch
2. Avoid - Local variable 'value_format_string' might be referenced before assignment

General makeup - thanks to PyCharm

---

TM1py/Utils/Utils.py
Tests/Cube.py

Reverts cubewise-code/tm1py#290
As we have `replace('%', '%25')` in two places `format_url` and `_url_and_body`... `%` becomes `%2525`
```Python
subset = Subset(subset_name='t% eeest', dimension_name='test %', hierarchy_name='test %',
expression="{TM1FILTERBYLEVEL({TM1SUBSETALL ([test %])}, 0)}")
tm1.subsets.create(subset)
```
URL: `https://adminhost:port/api/v1/Dimensions('test%20%2525')/Hierarchies('test%20%2525')/Subsets`
We should remove `replace` in any one place.

Revert 290 issue/fix create subset with ampersand

---

TM1py/Services/RestService.py
TM1py/Utils/Utils.py
Tests/Cube.py
Tests/Subset.py

Now escaping of illegal characters in object names happens exclusively in `format_url` method.
This way it also applies for ODATA URL references inside the JSON.

Move escaping of characters entirely to utils

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py
Tests/Cell.py

The `extract_cellset_raw` method did not use the `top` argument properly.
**Before PR:**
`Axes($filter=Ordinal ne 2;$expand=Tuples($expand=Members($select=Name);$top=5))`
**After PR:**
`Axes($filter=Ordinal ne 2;$expand=Tuples($expand=Members($select=Name;$top=5)))`
**Code to replicate:**
```Python
tm1 = TM1Service(****)
tm1.cells.execute_view_dataframe(cube_name='test', view_name='test', top=5, private=False)
```
Also the `extract_cellset_csv` method was not passing the `top` argument to `build_csv_from_cellset_dict` method.

Fix top argument usage in extract_cellset_raw

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py
Tests/Cell.py

New methods for getting `dict` from `MDX` or `view` created `cellset`.
```Python
tm1 = TM1Service(****)
mdx = "SELECT " \
"NON EMPTY {TM1SUBSETALL( [}Clients] )} on ROWS, " \
"NON EMPTY {TM1SUBSETALL( [}Groups] )} ON COLUMNS " \
"FROM [}ClientGroups]"
values = tm1.cells.execute_mdx_dict(mdx)
for key, value in values.items():
print(f'{key}:{value}')
values = tm1.cells.execute_view_dict(cube_name='}ClientGroups', view_name='Default')
for key, value in values.items():
print(f'{key}:{value}')
```

New methods

---

TM1py/Services/CellService.py
TM1py/Services/PowerBiService.py

`execute_power_bi` funtions are now called `execute_shaped` in `CellService`.
Dedicated PowerBI functionality is now exclusively available in `PowerBiService`.
`execute_shaped` functions are applicable for other use cases as well, as they
retrieve data in the shape of the query (MDX, View) while ignoring title
selections.

Renaming _power_bi functions in CellService

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py
Tests/Cell.py
Tests/Utils.py

Add optional `all_leaves_as_default` argument to `clear_with_mdx` function.
If the argument is passed as True, TM1py will accept incomplete MDX queries and complement it with the missing dimensions.
For the missing dimensions all leaves (`TM1FILTERBYLEVEL({TM1SUBSETALL([Product])}, 0)`) will be added to ROWS or COLUMNS.
This approach is fragile to a certain extend. The `not_referenced_dimensions`
are determined by comparing the titles of the dimension composition in the cellset and the WHERE selection in the MDX.
In order to deal with the fragility of the approach, the function is somewhat fussy about the MDX it accepts. The function will abort if
- MDX does not contain selections on ROWS and COLUMNS
- MDX does not contain either `ON 0` or `ON COLUMNS` (casing is ignored)
- MDX does not …

Add optional `all_leaves_as_default` argument

---

Tests/Subset.py
Tests/Utils.py

Removes deprecation warnings thrown in 5 tests. 
A first little step for https://github.com/cubewise-code/tm1py/issues/301

Replace assertEquals with assertEqual

---

Tests/Other.py
Tests/PowerBiService.py

I ran a few linters and found these modules were imported but not used, eg Pandas is imported but used via the power_bi module and doesn't need to be imported in entirety by Tests/PowerBiService.py.

Removed unused imports from a couple of tests

---

TM1py/Utils/Utils.py

Updates references to collections.* to collections.abc in accordance with deprecation warnings:
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
```
I think this is fairly straightforward but let me know if I'm missing something :)
All tests in Tests/Utils still pass after the change

Update from collections.* to collections.abc

---

TM1py/Services/CubeService.py
TM1py/Services/DimensionService.py
TM1py/Services/ElementService.py
Tests/Cube.py
Tests/Dimension.py
Tests/Element.py

Methods `get_number_of_elements`, `get_number_of_consolidated_elements` and `get_number_of_leaf_elements` are throwing errors.
**Code to replicate:**
```python
tm1 = TM1Service()
month_elements = tm1.elements.get_number_of_elements('Month', 'Month')
```
**Output:** `KeyError: '@odata.count'`
**Added new methods:**
`get_elements_by_level`
`get_number_of_cubes`
```python
tm1 = TM1Service()
month_elements = tm1.elements.get_elements_by_level('Month', 'Month', 2)
```
**Output:** `['Q1', 'Q2', 'Q3', 'Q4']`

Adding new methods and fixing element count methods

---

Tests/Cell.py
Tests/Utils.py

I really like the move to making pandas optional and wanted to make sure the tests could still run too when pandas isn't installed.
This PR uses the import logic from Utils/Utils.py and adds a decorator to skip the relevant tests. Tests can now be run without pandas installed without throwing an error and the tests are skipped with a message.

Skipped tests requiring pandas

---

Tests/Annotation.py

As part of https://github.com/cubewise-code/tm1py/issues/301, I've had a look at the tests for the annotations service as a starting point because it was a relatively simple class. It's still a bit rough but I thought I'd put it out there before getting too carried away. 
What I tried to do:
* Manage the fixtures a bit more cleanly and tried to ensure everything is cleaned up after each run
* Mapped the tests to the individual methods in the AnnotationsService (ie 5 tests instead of 3)
* Tested that each test could be run independently 
* Checked coverage
* Added some simple docstrings to explain what each bit is trying to do
A couple of things to note:
* The fixture creation and naming conventions could still be improved and possibly moved into helper functions shared across all test …

WIP - First look at Testing/annotations.py

---

TM1py/Utils/Utils.py
Tests/Cell.py
Tests/TestUtils.py
Tests/Utils.py

Actually, this might be a more elegant way of handling the pandas checks. I moved the decorator to the same place as ```require_pandas``` and aligned the code. I also removed the globals set in the test files as they aren't necessary.
I think this might be a way to approach a similar decorator for skipping tests were the required version is too low. 
part of https://github.com/cubewise-code/tm1py/issues/301

Move skip_if_no_pandas to utils

---

Tests/Cell.py
Tests/TestUtils.py

I've added another decorator that skips test where the version isn't high enough and applied it to some tests.

Add decorator to skip tests where version insufficient

---

TM1py/Services/CubeService.py
Tests/Cube.py

Going by these [release notes](https://www.ibm.com/support/knowledgecenter/SSD29G_2.0.0/com.ibm.swg.ba.cognos.tm1_rest_api.2.0.0.doc/r_restapi_v1_csdl_whats_new.html#restapi_v1_csdl_whats_new) I've added the require and skip_if_insufficient version decorators where the version isn't supported. 
All four tests were failing for me on 11.3 and will be skipped with these changes. I'm happy to just change the tests for now if you like but thought it might make sense to change CubeService.py at the same time.
Cheers
Alex

Add require version logic to CubeService methods and tests

---

Tests/Process.py

These tests cause the server being tested to crash (11.3). I think it's safe to mark them as requiring a greater version.
What do you think?
Cheers
Alex

Skip tests that crash the server on 11.3

---

TM1py/Objects/Process.py

As per the discussion in https://github.com/cubewise-code/tm1py/issues/309
I don't think this change breaks the functionality and suppresses a deprecation warning. 
What do you think? It's not urgent, on Python 3.8 it is still just throwing a warning.
Cheers
Alex

?s to start of str to remove deprecation warning

---

TM1py/Services/CellService.py
Tests/Cell.py

As discussed on https://github.com/cubewise-code/tm1py/pull/295#issuecomment-670947982 lets convert the return type from `Dict` to `CaseAndSpaceInsensitiveDict`

get_*_elements_value_dict methods now return CaseAndSpaceInsensitiveDict

---

Tests/Cell.py
Tests/Hierarchy.py
Tests/Security.py

I noticed a couple of the tests use pytest. I like pytest but since we're using unittest for 99% of the tests, I think it makes sense to replace these pytest methods with equivalent unittest logic.
What do you think?
Cheers
Alex

Change pytest.raises to unittest's assertRaises

---

Tests/PowerBiService.py
Tests/Security.py

I realised I broke the Security tests by removing a couple of imports erroneously, might have messed up the conflict resolution :|
Also removes unused import of os in the power BI service tests.
Cheers
Alex

Fix some imports in Tests

---

Tests/Application.py

Another little change to skip a couple of further tests that fail on my setup.
Note I couldn't find anything in the release notes to pinpoint this so might just be a point release bug but the error I get is below for reference. It might just be down to the way all the TM1 artifacts are arranged for these tests (which I still want to clean up) but thought it makes sense to use the version skip for now, especially if it's not causing an issue for others.
Cheers
Alex
```
Tests/Application.py:218: in run_test_document_application
self.tm1.applications.create(application=app, private=private)
TM1py/Services/ApplicationService.py:170: in create
url = format_url(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```

skip tests in applications that fail on 11.3

---

Tests/Chore.py

Another test to skip, as per comment here:
https://github.com/cubewise-code/tm1py/blob/e3e2c69a494d9cec5b2904c11ade3cd673ca9579/Tests/Chore.py#L127
It might just be the assert around the multiple/single commit mode so the test can possibly be split into two to test the rest of the functionality.

skip a test that fails <=11.7

---

TM1py/Utils/Utils.py

0 cells in REST API are returned as None.
We must not write None to CSV string, but "" in order to produce NaN in pandas dataframe

Avoid execute_dataframe method to fail over 0 cell

---

TM1py/Services/RestService.py
Tests/Security.py

new optional `impersonate` argument in `TM1Service`, to impersonate non-admin users. Useful to test security.
Fixes #353
``` python
ADDRESS = "localhost"
PORT = 12354
USER = "admin"
PWD = "apple"
SSL = True
with TM1Service(address=ADDRESS, port=PORT, user=USER, password=PWD, ssl=SSL, impersonate="Marius") as tm1:
print(tm1.dimensions.get_all_names())
print(tm1.whoami.name)
```

Add impersonation

---

TM1py/Services/ElementService.py

Fixes #381 
From the below image:
```python
consol_ele2 = tm1.elements.get_members_under_consolidation(tempdim, tempdim, "Total", 1, False)
consol_ele2 = tm1.elements.get_members_under_consolidation(tempdim, tempdim, "Total", 2, False)
```
will now return:
```python
['A', 'C', 'D', 'B']
['A', 'A1', 'A2', 'C', 'C1', 'C2', 'D', 'B', 'C', 'B', 'B1', 'B2', 'B3']
```

Update the depth variable to capture the correct level of elements

---

Tests/Cell.py

Hi Marius
I had a go at tidying up the tests for the cells service. 
* Moved global vars to class properties
* Re-structured fixtures to ensure idempotency
Some of the tests were failing sporadically when I randomised the test order (I use the pytest-randomly plugin for this, which is simple and effective for flagging up these issues). The fixtures could probably do with some further housekeeping but I think this is a good start. Let me know what you think.
Cheers
Alex
(relates to https://github.com/cubewise-code/tm1py/issues/301)

Cleaned up cells tests

---

TM1py/Objects/Subset.py
Tests/Sandbox.py
Tests/Subset.py
Tests/SubsetService.py
Tests/__init__.py

Hi Marius
I was looking at the subset code and tried a few things:
* split tests into Subset.py (just tests the objects) and SubsetService.py (tests the service)
* aligned the Subset from_dict method with the constructor to support missing values for optional args
* renamed the class in ```Tests/Sandbox.py```
* updated the ```Tests/__init__.py``` to include a few new files
Let me know what you think  :)
Cheers
Alex

Split subsets tests into two and a couple of other things

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py

Now always query `Updateable` property with `RuleDerived` property to work around issue in TM1

Work around RuleDerived cell property issue

---

TM1py/Objects/Git.py
TM1py/Objects/GitCommit.py
TM1py/Objects/GitPlan.py
TM1py/Objects/GitRemote.py
TM1py/Services/GitService.py
TM1py/Services/TM1Service.py
TM1py/Services/__init__.py
TM1py/__init__.py

This set of commits adds basic support for Git by adding a GitService and objects for Git, GitCommit, GitPlan and GitRemote. The code is based on a postman collection set I created to experiment with GIT and TM1 and has been working in my rather limited internal testing. 
I've tried to adhere to what I perceive to be the current software design patterns of tm1py. Feedback is welcomed, and please inform me if you want me to squash the commits or do other things to improve the merge. 
Fixes #156

Support for Git

---

README.md
TM1py/Services/ServerService.py

Include Query AuditLog Capability (#469)
Based on [this tutorial from ibm ](https://www.ibm.com/support/knowledgecenter/en/SSD29G_2.0.0/com.ibm.swg.ba.cognos.tm1_inst.2.0.0.doc/pa_nf_tm1_audit_logging.html), it was included `get_audit_log_entries` method. It follows the same structure pattern of `get_transaction_log_entries`.
Planning Analytics 2.0.8 or higher - (July 17, 2019)
This method can be called:
```
with TM1Service(address='localhost', port='xxxx', user="xxxx", password="xxxx", 
namespace=None,ssl=True) as tm1:
```
x = tm1.server.get_audit_log_entries(ObjectName='SYSTEM',
object_type='Server',
user='Admin', 
since=datetime.datetime.strptime('2020-12-01', "%Y-%m-%d") )
df = pd.DataFrame(x)
```
ID 	    TimeStamp 	    UserName 	    Description 	ObjectType 	ObjectName
0 	507 …
```

AuditLog Queries capabilities

---

TM1py/Services/MonitoringService.py
TM1py/Services/ProcessService.py
TM1py/Services/RestService.py

`cancel_at_timeout` can be passed to any function in TM1py.
Controls if operation in TM1 is aborted when timeout is reached.
Fixes #489

Introduce new cancel_at_timeout argument

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py
Tests/CellService.py

to control the structure of the result dictionary
- `values_only`
- `element_unique_names`
Through these optional arguments `execute_mdx` can return shape:
```
{('e1', 'e2'): 2}
```
instead of:
```
{('[d1].[e1]', '[d2].[e2]'): {'Value': 2}}
```

Add arguments to execute_mdx, execute_view

---

TM1py/Services/PowerBiService.py

Overriding default row header in dataframe returned by MDX to match the dimension name used in the drop duplicate operation.

Fix mismatch df header

---

TM1py/Services/MonitoringService.py

Add get_active_threads function to filter TM1 threads which are non-idle directly via REST end-point.

Add get_active_threads

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py
Tests/CellService.py

in `execute_view`, `execute_mdx `function rename `values_only` arg to
`skip_cell_properties` for sake of readability and clarity

Rename `values_only` argument

---

TM1py/Services/CellService.py
Tests/CellService_test.py

currently, linebreaks followed by the hashmark (`#`) break the
`write_through_unbound_process` function.
since turbo integrator doesn't write linebreaks to cells anyways, we may as
well remove them from the string.
Fixes #568

Remove linebreaks in values when writing with ti

---

TM1py/Services/CellService.py

Adding zero suppression for empty strings.
Instead of filtering only 0 and null values, '' have been added.

empty strings suppression in extract_cellset_raw

---

TM1py/Services/ProcessService.py

Hi @MariusWirtz  and @rkvinoth 
Sorry, I removed the previous MR as I obviously had redundant code. Here is my subsequent draft.
```python
with TM1.TM1Service(**config[ env ]) as tm1:
process = Process(name="Test_Process")
process.add_parameter(name="P0", prompt="logoutput message", value="Default")
process.prolog_procedure = "LOGOUTPUT('WARN', P0 ) ;LOGOUTPUT('WARN', P1 ) ;"
success, status, _ = tm1.processes.execute_process_with_return(process=process, P0="Here you go", P1="here we go again")
print("Process {}".format(status))
```

unbound process parameter support

---

TM1py/Services/CellService.py

don't foward deactivate_transaction_log and reactivate_transaction_log
needlessly through full stack.
pop them from kwargs after they are consumed in `manage_transaction_log`
decorator.
This way they are not forwarded to execute_process_with_return in use_ti
write mode.

Improve kwargs delegation through stack

---

TM1py/Utils/Utils.py

Allow simpler initiation of `CaseAndSpaceInsensitiveSet`:
```
from TM1py.Utils import CaseAndSpaceInsensitiveSet
items = CaseAndSpaceInsensitiveSet(["value1", "value2", "value3"])
```
As opposed to:
```
from TM1py.Utils import CaseAndSpaceInsensitiveSet
items = CaseAndSpaceInsensitiveSet()
for value in ["value1", "value2", "value3"]
items.add(value)
```
Or:
```
from TM1py.Utils import CaseAndSpaceInsensitiveSet
values = ["value1", "value2", "value3"]
items = CaseAndSpaceInsensitiveSet(*values)
```

Make custom set easier to use

---

TM1py/Services/ProcessService.py
Tests/ProcessService_test.py

`get_last_message_from_processerrorlog` is returning the response code instead of the content in text fomat.
This pull request is to fix that.
Added a test case as well.
fix for #625

get_last_message_from_processerrorlog should return text

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py
Tests/CellService_test.py

Handy new argument to skip cells that are not updateable.
Fixes #651

Add `skip_non_updateable` arg to write function

---

TM1py/Services/CubeService.py
TM1py/Services/ProcessService.py

**Process Search:** added 2 functions to search for string in process body and to search string in process name
_search_string_in_body_ will look for string anywhere in prolog, metadata, data epilog. UseCase: find TI process(es) that imports a csv file with name "x.csv"
_search_string_in_name_ will search for string anywhere in process name; two parameters: name_startswith and name_contains. name_contains can be an iterable list of strings to search with AND operator. UseCase: find TI process(es) that start with "Load" and have string "GL" anywhere in process name.
**Cube Search:** added 2 functions to find list of cubes that contain specified dimension or wildcard search on dimension name
_get_names_with_dimension_ will return list of cubes that contain specified dimension, optional …

Cube and Process Search functions

---

TM1py/Services/CubeService.py
TM1py/Services/ProcessService.py
Tests/CubeService_test.py
Tests/ProcessService_test.py

Align search function names. Always prefix with `search_`
Successor of #658

Add tests for new search functions

---

TM1py/Services/ChoreService.py
Tests/ChoreService_test.py

Added two functions for searching for chores based on process name or defined parameter value(not parameter name and not the parameter default set in the TI process) in the chore configuration. I took a stab at some test cases as well.

Chore search methods

---

TM1py/Services/CellService.py
TM1py/Services/ElementService.py
TM1py/Utils/Utils.py
Tests/CellService_test.py

related to https://github.com/cubewise-code/tm1py/issues/604
This draft pull request attempts to resolve the current limitation of the `iterative_json_parsing` argument, that it can't be used in conjunction with `include_attributes` on the `execute_mdx_dataframe` function.

Allow iterative_json_parsing in conjunction with include_attributes

---

TM1py/Services/ElementService.py

Fail attribute delete operation silently when hierarchy does not exist

Fail attribute delete operation silently

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py

Current csv string creation can produce invalid strings in the event of something like the delimiter being present in a value.  Propose using the csv module to create these strings instead of just concatenating values together, to ensure correct strings are created.
Adds argument for csv_dialect to allow user to provide settings for all possible formatting options.  If not provided will create dialect based on existing value_separator and line_separator arguments, so they will be used in the event that a user has passed custom values.

Use csv module to create csv strings

---

TM1py/Services/ApplicationService.py
Tests/ApplicationService_test.py

Add `rename` function to ApplicationService

---

TM1py/Objects/ChoreStartTime.py

It attempts to fix 2 issues:
1. We cannot set minute to 0, because "if minute:" will evaluate to False. The same goes for other parameters.
2. We would get "ValueError: day is out of range for month" if we set month to 2 while the original day is 31, vice versa.

Fix set_time of ChoreStartTime class

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py

to `extract_cellset_csv` function.
Fix `delete_cellset` argument in function.

Add `include_headers` argument

---

TM1py/Objects/Dimension.py
TM1py/Objects/Hierarchy.py

Allows this:
``` python
month_dimension = tm1.dimensions.get(dimension_name="month")
with open("raw/month.json", "w") as file:
file.write(month_dimension.body)
with open("raw/month.json") as file:
month_dimension = Dimension.from_json(file.read())
month_dimension.name = "NUK month"
tm1.dimensions.update_or_create(month_dimension)
```

Necassary changes to create dim from json file

---

TM1py/Utils/Utils.py

- Use dict(zip(keys, values)) instead of a for loop
- Use itertuples to make each row until last column of the dataframe into a tuple
Efficiency Statistics (1000 iterations)
Larger dataframe:
Comparison in markdown tables:
Current (before commit/merge)
|      |   length: 1000 width: 3 |   length: 1000 width: 13 |   length: 5000 width: 3 |   length: 5000 width: 13 |   length: 15000 width: 3 |   length: 15000 width: 13 |
|:-----|------------------------:|-------------------------:|------------------------:|-------------------------:|-------------------------:|--------------------------:|
| mean |                  0.0049 |                   0.0179 |                  0.0477 |                   0.1101 |                   0.1464 |                    0.3459 |
| std  |                  0.0059 | …

perf: improve performance of build_cellset_from_pandas_dataframe

---

TM1py/Services/ElementService.py
Tests/ElementService_test.py

Add `get_parents` function to `ElementService`

---

TM1py/Objects/Cube.py
Tests/Cube_test.py

Accept str for rules update on Cube object

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py
Tests/CellService_test.py

duplicates in string values are accepted (last one wins)
duplicates in numeric values are aggregated

Handle duplictes in df to dict transformation

---

TM1py/Services/CubeService.py
TM1py/Services/DimensionService.py
TM1py/Services/ProcessService.py
Tests/CubeService_test.py
Tests/DimensionService_test.py
Tests/ProcessService_test.py

Sorry for the multiple pull requests that were subsequently closed. I was working on separated, nested branches and created a pull request for each individually before simply merging them all into one here.
1. new function search_for_rule_substring will return all cubes with substring in rules
2. added skip_control_cubes parameter to multiple CubeService functions e.g. get_all_names, get_number_of_cubes
3. added skip_control_dims parameter to DimensionService functions get_all_names and get_number_of_dimensions
4. attempted update to test cases

Cube Rule search function and new skip_control parameters

---

TM1py/Objects/ProcessDebugBreakpoint.py
TM1py/Services/ProcessService.py

Initial commit with ProcessDebugBreakpoint object and additional debug actions in ProcessService from the existing StepOver and StepOut.
I've also added a function `ti_formula()` to replicate the evaluate option of the TI variable editor in architect/perspectives. It's not a light-weight operation as it involves creating a temporary TI in the same fashion as the `execute_ti_code()` function. It then starts a debug session, sets a breakpoint, and runs until the breakpoint is hit, returning the variable value at that breakpoint before cleaning up the temp TI. The idea for this came from a colleague asking me how to evaluate a variable formula in the PAW TI editor like they frequently do in architect. I wasn't aware of similar functionality in PAW TI editor so created this as a stop-gap …

ProcessDebugBreakpoint: Initial commit

---

TM1py/Services/CellService.py
TM1py/Utils/Utils.py
Tests/CellService_test.py

It is a bad practice to use the `execute_mdx_dataframe` function with `include_attributes` as True, while omitting the PROPERTIES in the MDX query.
It is bad because the response JSON is arbitrary and depending on what
attributes exist and don't exist in the TM1 model.
Instead of attempting to work with this flawed response JSON,
TM1py must raise an error demanding that the user
requests attributes properly by the use of PROPERTIES in the MDX query.
Solves #507 and #718

Raise ValueError if csv is not df compatible

---

TM1py/Services/CellService.py

This code allows for automatic alignment of float numbers when writing back through unbound process to avoid "Number too big" errors during writeback.

Alignment of float numbers when writing back through unbound process

---

TM1py/Services/ElementService.py
Tests/ElementService_test.py

New features to resolve https://github.com/cubewise-code/tm1py/issues/758

Feature element functions

---

TM1py/Services/ElementService.py
Tests/ElementService_test.py
Tests/config.ini

Added the ability to select different methods for the Element functions. This requires an update to MDXpy

Update Element Parent and Ancestor methods

---

TM1py/Utils/Utils.py
Tests/CellService_test.py

The new change allows this:
``` python
with TM1Service(base_url="https://localhost:12354", user="admin", password="apple") as tm1:
mdx = """
SELECT
NON EMPTY Tm1FilterByLevel({TM1SubsetAll([d1])},0) on 0,
NON EMPTY Tm1FilterByLevel({TM1SubsetAll([d2])},0) on 1,
NON EMPTY Tm1FilterByLevel({TM1SubsetAll([d3])},0) on 2,
NON EMPTY Tm1FilterByLevel({TM1SubsetAll([d4])},0) on 3,
NON EMPTY Tm1FilterByLevel({TM1SubsetAll([d5])},0) on 4
FROM [c5]
"""
cells = tm1.cells.execute_mdx(mdx, element_unique_names=False, skip_cell_properties=True)
for elements, value in cells.items():
print(elements, value)
```
```
('e1', 'e1', 'e01', 'e01', 'e01') 4
('e1', 'e1', 'e01', 'e02', 'e01') 1
('e1', 'e1', 'e01', 'e01', 'e02') 2
('e1', 'e1', 'e01', 'e02', 'e02') 3
```

Allow multi axes queries in `execute_mdx` function

---

TM1py/Services/ElementService.py
Tests/ElementService_test.py

I've added new functions to element service for string and numeric elements. I've also added a `get_parents_all_elements` function which is similar to `get_parents` but instead of taking an element argument, will return parents for all elements in dim.
I've taken a stab at the tests for these new functions. I wrapped all of the string element testing in one function because I add a string function to test and then immediately delete. This seemed better than adding it when the class is created, seemed like it could mess up some other tests.

Element functions

---

TM1py/Objects/GitProject.py
TM1py/Services/GitService.py

In these commits you will find the GitProject.py that has the class, properties and methods to handle the tm1project and the GitService that incorporates the GitProject objects and adds the ability to get, put and delete the tm1project from/to the server.
This is a first draft so we can make changes along the way. I also have some of the tm1project sections defined as classes (like object, task and deployment) but I'm not done with them.

Adding tm1project to the Git service

---

TM1py/Objects/ProcessDebugBreakpoint.py
TM1py/Services/ProcessService.py

I updated the ProcessDebugBreakpoint object and debug_add_breakpoint function to be able to add multiple breakpoints as requested in issue:https://github.com/cubewise-code/tm1py/issues/764.
I also added some new functions for getting current breakpoint details like procedure and current line number as well as new step_in function to complement the step_over, step_out, and continue functions
I shamefully did **not** update any tests around the breakpoint.

Breakpoint refactor & new functions

---

TM1py/Services/CellService.py

Hi together,
I recently had some problems while trying to read single values from a cube with the get_value function.
This was due to some elements having commas in their names.
While this should normally not be case if elements are named properly, it could happen especially if some aliases are added from other datasources. The get_value function in the CellService is not able to handle that at the moment.
It would be nice to change the default delimiter setting if needed. I propose a change in this pull request but it would have to be added also to some other functions in the CellService (e.g _compose_odata_tuple_from_string).
Best regards
Tobias

Add alternative separators to get_value function

---

TM1py/Services/CellService.py

Hey,
In addition to #801 I added the alternative separators for the remaining functions to keep the interface consistent.
The rule and feeder checking functions have the possibility to pass an Iterator instead of a string. That could also make sense for the ```get_value``` function and would make string splitting obsolete. Maybe we could pass some kind of data structure that allows for the definition of multiple hierarchies too.
Best regards
Tobias

Add alternative separators for element strings of the remaining functions in CellService

---

TM1py/Services/RestService.py
TM1py/Utils/Utils.py

Hi, @MariusWirtz 
I have tested four methods and they look good to me. 
The usage of this parameter is similar to the async one. If both are specified, then async_requests_mode is used by default.
`with TM1Service(address, port, ssl, user, password, namespace, async_requests_mode=True, tcp_keepalive=True) as tm1:`
As you can see, the TCP keepalive method captures the response a bit faster (<1s) than the async mode and since it is operating at TCP layer level, it would be more efficient (no polling and no more connections) than the async method at HTTP layer level, I suppose. 
I don't have other cloud environments to test. If someone can confirm it in other environments, it would be good. Thanks.

Enable TCP keepalive option for executing long-run requests

---

TM1py/Services/CubeService.py
TM1py/Services/ServerService.py

This branch has two new updates in terms of additional features. 
i) A new function **cube_save_data** is added in CubeService.py to serialize a cube using TM1Py. This requires cube name as a parameter and returns the response code.
ii) A new function **delete_persistent_feeders** is added in ServerService.py to delete all persistent feeders using TM1Py. This does not require any parameter and returns the response code.
Both these functions executes a temporary ti process to execute CubeSaveData and DeleteAllPersistentFeeders functions respectively.

Additional features - CubeSaveData and DeleteAllPersistentFeeders

---

TM1py/Services/CellService.py
Tests/CellService_test.py

Hi together,
@MariusWirtz 
We discussed the option to pass element coordinates as Iterators to the ```get_value()```-function. That would remove the need to specify special separators for the element string.
You also had the idea to use the MDXpy ```Member``` object. I tried that and it worked out really nice! :)
It also simplifies the building of the MDX statement, because it provides the ```unique_name``` directly.
This could be used to create the ```Member``` directly from the splitted strings too. After that the MDX query can be build independently of the input type always from the ```Member``` object.
So I did some little restructuring to use the ```Member``` consistently throughout the function.
The ```get_value``` function is now callable without hierarchies like this:
```python …
```

Add option to pass element selection as iterator in get_value function

---

TM1py/Services/ElementService.py
TM1py/Services/PowerBiService.py
Tests/ElementService_test.py
Tests/PowerBiService_test.py

Implement `get_elements_dataframe` function

---

TM1py/Services/ServerService.py
Tests/ServerService_test.py

It's possible to filter the transactionlog entries with a lambda expression: Tuple/any(t: t eq 'filter value')
The function get_transaction_log_entries accepts kwargs so we could  add a section to the log_filter list in order to generate a lambda expression for the query:
` get_transaction_log_entries(reverse=True, user='Admin', cube='plan_BudgetPlan', tuple={'105': 'eq', '405': 'eq', '41101': 'ge'})`
tuple is a dict with 'filter value' as key and a operator as value. 
This could be extended to a lambda all expression by defining a lambda_method parameter which defaults to "any" but can changed to "all".
What do you think?

adding lamda expression to filter tuple

---

TM1py/Services/ServerService.py
Tests/ServerService_test.py

@ldelberg please approve.
For backward compatibility, I moved the elements as the last argument in the function.
I wonder how we should support position-based filtering in the function once the REST API allows for it.
I am not sure if we could manage it through the same argument. Maybe we introduce two arguments:
- `element_tuple_filter`
- `element_position_filter`
```
element_tuple_filter={'2020': 'gt', 'Actual': 'eq', 'Revenue': 'eq'}
```
```
element_position_filter={
0: {'2020': 'gt'},
2: {'Actual': 'eq', 'Budget': 'eq'},
7: {'Revenue': 'eq'}
}
```
What do you think?

Order args in `get_transaction_log_entries`

---

TM1py/Objects/GitProject.py

when loading a tm1project from file the tm1projecttask was repeating the task property: "Tasks": {"init_new_model": {"Process": "Processes('Processes('sys_initialize_new_model')')"}, "reset_instructions": {"Process": "Processes('Processes('sys_file_instructions_reset')')"}} Also the Chores option didn't have the "Chores" property fixed at the beginning of the string

fix to tm1projecttask

---

TM1py/Objects/Sandbox.py
TM1py/Services/SandboxService.py
Tests/SandboxService_test.py

Added load/unload sandbox functions. Also added Active, Loaded, Queued properties to sandbox object. I did not change the sandbox body, so all existing tests should still pass. I've taken a stab at adding tests for the new functions and properties.

Sandbox updates

---

TM1py/Services/RestService.py
TM1py/Services/TM1Service.py

Fixes https://github.com/cubewise-code/tm1py/issues/855

Reconnect on session timeout

---

TM1py/Services/ElementService.py
Tests/ElementService_test.py

Support hierarchies in get_elements_dataframe

---

TM1py/Services/CellService.py

**What**
Allows tm1py user to specify the infer_dtype argument on tm1.cells.execute_mdx_dataframe_shaped. 
If infer_dtype=True, tm1py lets pandas decide the dtype of each column. If infer_dtype=False, it will default to the current behaviour and load all columns as string unless there is no columns (see "if not number_columns") or no rows (see "if not number_rows") (in which case tm1.cells.execute_mdx_dataframe_shaped will already infer the dtype automatically).
If the infer_dtype argument is not specified, tm1.cells.execute_mdx_dataframe_shaped will default to its current behaviour equivalent to infer_dtype=False.
**Why**
Default behaviour requires to mutate dtypes after retrieving dataframe. If all columns are numerical, the dataframe retrieved would still have string values. This PR …

Allow dtype to be inferred by pandas with argument infer_dtype in execute_mdx_dataframe_shaped

---

TM1py/Services/CellService.py
TM1py/Services/ObjectService.py
TM1py/Services/ViewService.py
TM1py/Utils/Utils.py
Tests/CellService_test.py
setup.py

Solves #884
Add `use_blob` to `execute_mdx_csv`, `execute_mdx_dataframe`, `execute_view_csv`, `execute_view_dataframe`
Reduces time to execute MDX by 20-40%
Reduces time to execute NativeView by 40-50%
Reduces memory footprint of Python process significantly in all cases.

Implement `use_blob` for `execute_mdx_csv` function

---

TM1py/Services/CellService.py
TM1py/Services/ViewService.py
Tests/CellService_test.py
Tests/ViewService_test.py

- eliminate an issue that TI considers elements in title subsets for data source
- allow usage of `execute_view_csv` and `execute_view_dataframe` on MDX view

Make execute_view_csv with use_blob robust

---

TM1py/Services/CellService.py
TM1py/Services/ElementService.py
TM1py/Services/PowerBiService.py
TM1py/Utils/Utils.py
Tests/PowerBiService_test.py
Tests/ServerService_test.py
Tests/Utils_test.py

Inspired by
https://github.com/Kevin-Dekker/tm1py/commit/8ab9901b0c04c63c221077d8cdfd1d20f113e62e#diff-5242c6c19161de7f529a4e5b0d0b33ca9c15f69be65fa5409881b3d8310ff655R2799-R2802
`execute_mdx_dataframe`, `execute_view_datafame` can be run with `shaped=True` to retrieve a similar but not fully equivalent result to `execute_mdx_dataframe_shaped`.
This allows retrieving a shaped data frame while specifying options that are not available in `execute_mdx_dataframe_shaped`. One example is the usage of `use_iterative_json=True` and `use_blob=True` which optimizes memory usage during string to json / dict conversion prior to the creation of the data frame.
Fixes #888

Introduce shaped arg to execute_mdx_dataframe

---

TM1py/Services/CellService.py
Tests/CellService_test.py

A concept to allow simple proportional spreads in case any of the elements (coordinates) is c level and the value to write is numerical when using use_ti or use_blob.
**Usage**
Specify allow_spread=True and write to one or more c level elements. 
**Tests** 
Scripts included in tm1py/Tests, further tests required.
**Limitations**
- Does not increment, 
- Speed not compared between allow_spread=True and allow_spread=False.
- Implementation on use_ti not very clean. Although, it's in the same style as the current code in the write_through_unbound_process function.

Spreading on write with use_blob & use_ti

---

TM1py/Services/RestService.py
TM1py/Services/TM1Service.py

Accept `proxies` argument in `TM1Service` constructor
@Cubewise-gtejeda 
please upgrade to this branch and test it.
```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/feature/support-proxy.zip
```
``` python
proxies = {
'http': 'http://proxy.example.com:8080',
'https': 'http://secureproxy.example.com:8090',
}
with TM1Service(**params, proxies=proxies) as tm1:
print(tm1.server.get_product_version())
}
```

Add `proxies` arg to `TM1Service`

---

TM1py/Services/CellService.py
TM1py/Services/ChoreService.py
TM1py/Services/RestService.py
TM1py/Services/ServerService.py
TM1py/Utils/Utils.py

Show parameters on decorated functions in PyCharm

---

TM1py/Services/CellService.py
Tests/CellService_test.py

1. Fixed wrong position of brackets in extract_cellset_raw extract_cellset_metadata_raw 
2. The name of the additional "tricky" parameter "top_rows" has been changed to "top_tuples" to avoid misunderstandings
3. A new test has been added to check execution of  execute_mdx_raw with "top" parameter

Fixed wrong position brackets in extract_cellset_raw (ref to 883 issue)

---

TM1py/Services/ElementService.py
Tests/ElementService_test.py

Useful when synchronizing sub hierarchies between instances
Fixes #915

Add `get_edges_under_consolidation` Function

---

TM1py/Services/ElementService.py

Currently only a element by element delete method exists in the element service. This is really slow when iterating over. 
The Odata v4 rest api does not support deleting multiple elements at once, so this implementation uses a workaround suggested by Hubert Heijkers (https://community.ibm.com/community/user/businessanalytics/communities/community-home/digestviewer/viewthread?GroupId=3067&MessageKey=43fd0611-5665-4367-b250-f4278dba6ac6&CommunityKey=8fde0600-e22b-4178-acf5-bf4eda43146b&tab=digestviewer). The hierarchy object is patched instead of trying to delete a collection of entities.

Add method to delete elements

---

TM1py/Services/ElementService.py
TM1py/Services/HierarchyService.py
Tests/HierarchyService_test.py
Tests/config.ini
setup.py

Create or Update Hierarchy based on data frame
Create or update an existing hierarchy based on data frame.
Attribute columns can be suffixed with a,s, or n to control the
attribute type.
Edges and Weights are created according to the provided level columns
Function supports
- multiple parents
- duplicate records
- explicit or implicit (through level columns) consolidation records
- optional unwind before manipulation
- attribute update
- imbalanced hierarchies
Function checks df before creation for:
- invalid alias
- contradictory records

Add `update_or_create_hierarchy_from_dataframe` Function

---

TM1py/Services/CellService.py
Tests/CellService_test.py

Method to expose CellSet Partitions. The functions tm1.GetPartition returns a collection of CellSet Cells. Therefore partitioning could not be easily integrated into other "execute...." functions. To do so it would require the ability to view the axis information for the given partition, that is not available directly in the API. Enabling it would require TM1py to stitch together the partitions based on cell ordinals. There is no direct way to navigate from a cellset cell to the cell address (https://www.ibm.com/docs/en/cognos-tm1/10.2.2?topic=1022-schema#restapi_v1_csdl_entitytype_CellsetCell)

Created a new method to expose Cell Partitioning

---

TM1py/Services/CellService.py
Tests/CellService_test.py

New extract_cellset_axes_raw_async and extract_cellset_cells_raw_async were added to extract raw data from TM1 asynchronously. Demonstrate efficiency in retrieving large datasets with > 1M cells and can be further used to create asynchronous execute_mdx.
extract_cellset_axes_cardinality was also added to retrieve cellset cardinality

New extract_cellset_axes_raw_async, extract_cellset_cell_async and extract_cellset_axes_cardinality

---

TM1py/Services/CellService.py
Tests/CellService_test.py

Implement `extract_cellset_async` and expose function through `execute_mdx` and `execute_view` leverages `extract_cellset_axes_raw_async` and `extract_cellset_cells_raw_async`functions
Still lacking test cases but performance improvements are already measurable.

Implement extract_cellset_async

---

README.md

Hi, 
there are typos in the usage examples. The method _get_product_version_ is written with an capital V _get_product_Version_ which is wrong.
When you run the examples, you recieve the following error: AttributeError: 'ServerService' object has no attribute 'get_product_Version'. Did you mean: 'get_product_version'?

Docs: Fix syntax error in the usage examples in the readme

---

TM1py/Services/CubeService.py
TM1py/__init__.py

Add VMM and VMT methods to the cube service.

Feature update cache controls

---

TM1py/Objects/Process.py

V12 throws error on retrieving process fields that no longer exist.

process field not available in v12

---

TM1py/Services/RestService.py
TM1py/Services/TM1Service.py

Hi, @rclapp , @MariusWirtz 
As discussed, I have removed the parameter for v12 in cloud environment going forward. I tested it with CP4D v12 version and it looks good to me. Please review and help to approve it. Thanks.

Remove tcp_keepalive parameter

---

TM1py/Services/ApplicationService.py

Hi,
I have been working with Applications (Websheets) and I have created 2 useful functions to work with them to be able to update/sync Applications between TM1 instances:
get_names - returns all the applications in given path 
update_or_create - takes care of the applications that are not present in new model. 
On a side note - for Excel websheets the "create" only creates blob file instead of proper Excel fie in }Externals, while "update" updates Excel file correctly. It seems that REST API is not reflecting all the options that are possible with the Websheets in older TM1 Clients (Copy vs. Add as reference etc.) Has anyone come to that point too?
Thanks,
Tomas

Update ApplicationService.py to support application update or create

---

Tests/AnnotationService_test.py
Tests/CellService_test.py
Tests/ChoreService_test.py
Tests/CubeService_test.py
Tests/DimensionService_test.py
Tests/ElementService_test.py
Tests/FileService_test.py
Tests/HierarchyService_test.py
Tests/ProcessService_test.py
Tests/SandboxService_test.py
Tests/TM1pyDict_test.py

The methods `setUp()` and `tearDown()` are not meant to be class methods. I have double checked the [docs](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp) and can't find any reason to declare them as class methods.
All tests run without failures after these changes. 
This PR contains:
- Removed @classmethod decorators for `setUp()` and `tearDown()`
- Renamed the argument from `cls` to `self`

Fix: Changed setUp and tearDown from class method to object method

---

.gitignore
TM1py/Services/AuditLogService.py
TM1py/Services/MessageLogService.py
TM1py/Services/ThreadService.py
TM1py/Services/TransactionLogService.py
TM1py/Utils/Utils.py
Tests/ServerService_test.py

I noticed that some unit tests failed in my development environment. So I tried to fix everything. When it was beneficial, I refactored the code beforehand to reduce duplicated code.

Fix all unit tests to run successfully

---

TM1py/Services/RestService.py

Determining whether a user is an admin based on the name is is simplified now
* Access to the `_user` property instead of multiple accesses kwargs.get('user')
* Use only one if statement with two conditions instead of multiple if statements
* "Default" value None moved to the top
* Removed method `_determine_is_admin` because the result was always overwritten afterwards
* Less code
Tests were passed successfully
```
============================================================= test session starts =============================================================
platform win32 -- Python 3.11.7, pytest-8.1.1, pluggy-1.4.0
rootdir: D:\dev\tm1py_onefloid
configfile: pyproject.toml
plugins: anyio-4.2.0, xdist-3.5.0, time-machine-2.13.0     
...
========================================== 816 …
```

Refactor: Simplified is_admin determination

---

TM1py/Services/ProcessService.py
TM1py/Services/RestService.py
Tests/ProcessService_test.py

**1126:**
Timeout is a parameter in the  request function, therefore the kwargs.get('timeout', self._timeout) would never get the specified value.
Also for consistency adding the timeout parser to default it to the class._timeout value if not provided.
**1128:** 
Adding the return_async_id to the **execute_process_with_return** so that it has the same functionality and signature as the **execute_with_return**
linkages for github:
this fixes #1126 and adds #1128 as well.

Fixing #1126 and#1128 - timeout is an explicit parameter hence kwargs(timeout) does not work, adding request_async_id in execute_process_with_return

---

TM1py/Services/ElementService.py
Tests/ElementService_test.py

Add feature to lock or unlock element.

Add element lock and unlock

---

TM1py/Services/ElementService.py
Tests/ElementService_test.py

Speed ​​up execution time by removing redundant elements specification when building mdx for attribute extraction.

Speed up get_elements_dataframe 

---

Tests/AnnotationService_test.py

At the moment it is not possible to run the whole test suite in parallel because tests in one test scripts often reuse the TM1 objects. 
This MR enables parallel testing of the AnnoationService by creating an unique test cube and unique test dimensions for each test run. There is a little bit more overhead now. But in most cases the multi worker test should outperform the single worker tests.
This MR continues the work of PR #1105

Tests: Enables parallel testing of AnnotationService_test

---

TM1py/Exceptions/Exceptions.py
TM1py/Services/FileService.py
Tests/ApplicationService_test.py
Tests/CellService_test.py
Tests/ChoreService_test.py
Tests/CubeService_test.py
Tests/ElementService_test.py
Tests/FileService_test.py
Tests/ManageService_test.py
Tests/MonitoringService_test.py
Tests/ProcessService_test.py
Tests/SecurityService_test.py
Tests/Utils.py
Tests/Utils_test.py

This PR improves the version checks in `FileService.py` and is inspired by issue #1123  :
* Fix: setUpV12 should only be called for v12, otherwise every test is skipped in lower versions f12c49d6e8dcd6f20702d6459b4bc41152f5ae9d
*  Fix: Added minimum required versions to file service c13bf1cdb852fd27cabad13ef78933ff20e3c166
* Feature: Added optional feature parameter for explaining why TM1pyVersionException is raised bd33d2abbbfbbadd1ad3c0ed21035a6c4b9b7ffc
* Fix: Raise error if subfolder feature is not supported by version f24c52d9d34500ceceb6d04588711acee5070c64
*  Refactor: Clean up not necessary f-strings e4b4629f3f60447573b27c14919436088a306a92
I couldn't run the tests against a tm1 server v12.

Fix: Improve version checks FileService

---

TM1py/Services/HierarchyService.py

`remove_edges_under_consolidation()` is not case and space insensitive at the moment, this fix would allow the function to be case and space insensitive. 
e.g. Element name "**Parent1**", "**parent 1**", "**Parent   1**", "**PARENT1**" would be treated in the same way.
Added/modified coding in **HierarchyService.py** to allow the function to work in case and space insensitive nature.
```
from TM1py.Utils.Utils import case_and_space_insensitive_equals, format_url, CaseAndSpaceInsensitiveDict, \
CaseAndSpaceInsensitiveSet, CaseAndSpaceInsensitiveTuplesDict, require_pandas, require_data_admin, \
lower_and_drop_spaces, require_ops_admin, verify_version
```
...
```
def remove_edges_under_consolidation(self, dimension_name: str, hierarchy_name: str,
consolidation_element: str, **kwargs) -> …
```

Fix 1174: Bug fix to compare and allow case and space insensitivity for remove_edges_under_consolidation()

---

TM1py/Services/ElementService.py
TM1py/Services/HierarchyService.py

additional feature added based on question #1184, now `delete_edges()` has params to delete a large number of edges from a hierarchy using flat file (**.blb**) based unbound TI. 
`delete_edges()` can now be called with additional params _use_blob_ and _remove_blob_, both of type bool. Using this params would write the edges in "parent","child" format in a flat file (**.blb**). v12 check added to always append **.blb** at the end. An unbound TI process would be created to read this file, and use `HierarchyElementComponentDelete()` to delete the edges.
Please note, additional imports are added at the beginning of ElementService.py apart from the specific code. The process would need data admin and ops admin to execute. 
```
@require_version("11.4")
def delete_edges(self, dimension_name: …
```

Feature-1184- delete edges using blob

---

TM1py/Services/FileService.py
Tests/FileService_test.py

Fixes TM1 v12 (in PA aaS) constraint of 200 MB max file size in file update / create endpoints
Speeds up file upload through parallelization of multi-part upload.

implement mpu file upload

---

TM1py/Services/TM1Service.py
Tests/DimensionService_test.py
Tests/MonitoringService_test.py

This Pull Request introduces lazy initialization for MonitoringService and ServerService, effectively reducing the occurrence of warnings related to these deprecated services. By instantiating these services in TM1Service only when they are actually needed, we minimize the warnings for the majority of use cases where these services are not used.
Furthermore, this PR suppresses expected warnings in tests: This allows the tests to run without cluttering the output with warnings that were anticipated.
* Cleaner Output: By avoiding unnecessary warnings, the console output during development and testing is cleaner and easier to read.
* Focus on warnings where developer action is required.
Please note that this implementation is not thread-safe. If needed, we have to rewrite some parts of the …

Implement Lazy Initialization to Prevent Warnings for Deprecated Services

---

TM1py/Services/FileService.py
Tests/FileService_test.py

MPU upload fails on empty files. 
TM1py must upload empty files without MPU.

Create empty files without mpu

---

TM1py/Utils/Utils.py
Tests/Utils_test.py

To keep the functionality of replacing na_values with ['', None]
not very sure "Value" column
ran test:
`pytest -k "execute_mdx_dataframe or execute_view_dataframe or extract_cellset_dataframe or build_dataframe_from_csv"`
close #1151

Fix 1151 element named none

---

TM1py/Services/RestService.py
TM1py/Services/TM1Service.py
TM1py/Utils/Utils.py

Usage: 
```python
context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
context.check_hostname = False
context.options |= ssl.OP_NO_SSLv3
ciphers = "HIGH:!aNULL:!MD5"
context.set_ciphers(ciphers)
tm1_params = {
"address": "localhost",
"port": 12354,
"user": "admin",
"password": "apple",
"ssl": True,
"ssl_context": context # new parameter for custom ssl
}
with (TM1Service(**tm1_params)) as tm1:
server_name = tm1.server.get_server_name()
print(server_name)
```

Added ssl_context param that allows to define custom ssl context for tm1 connection

---

TM1py/Objects/ChoreStartTime.py

Previously there was a bug where the timezone offset would be interpreted as the seconds e.g. UTC+2:00 would result in the chore value having 02 seconds in the schedule which was incorrect.
Updated from_string to always include seconds. Where seconds are not retrieved from TM1 as TM1 uses an ISO standard where 0 seconds are dropped, TM1Py will return 00 as seconds.

Timezone in Seconds component corrected and format aligned to always include seconds

---

TM1py/Objects/Process.py

Added a property "all_procedures". This property is not mandatory, but a helpful shorthand. I imagine many people want the entire TI code in one string, and so have to write something like `<Process>.prologue_procedure + <Process>.metadata_procedure + <Process>.data_procedure + <Process>.epilogue_procedure` which when done frequently seems unnecessarily clunky. This change provides minimal impact on TM1py while providing the user a cleaner option.

Add "all_procedures" to property Process in Process.py

---

TM1py/Services/RestService.py

Can use parameter "user" or "username" as discussed in TM1py weekly meeting :)

Update RestService.py to allow "user" or "username" param

---

TM1py/Utils/Utils.py
Tests/Utils_test.py

Adding a short function to sort lists. Use case (for me) is sorting of hierarchy names within dimensions, excluding certain hierarchies, such that these hierarchies could be migrated.

reorder_with_priority: revised code after Copilot suggestions

---

TM1py/Objects/Hierarchy.py
Tests/Hierarchy_test.py

pass leaves only parameter to recursive function
