- TM1py.py
1. Replace binary line feed using \r  [fix errors on windows plattform, python 3.5]
2. Add preliminary support for
3. Fix missing 'return response' for create_core_task
> Minor fixes and additions

- TM1py/Services/CellService.py
Added a new function to the CellService that returns the number of cells as a float. Should make validation easier prior to writing large CellSets back.
> New function to return number cells in a CellSet

- TM1py/Services/CellService.py
Corrected return type to be int and corrected for response content issues.
> Updated CellService get_cellset_cells_count 

- TM1py/Services/ElementService.py
Added new method to the ElementService to retrieve all members under a consolidation. Can be used to create a local replacement for ELISANC
> Added new method to the ElementService to retrieve all members under a consolidation

- TM1py/Objects/Process.py
Removing just a variable in self._variables in not enough. Need removing exact VariableUIData from self._variables_ui_data.
> Added removing from VariableUIData

- TM1py/Objects/Process.py
Use "\f" instead of "\r". Using "\r" creates a variable of the format Ignore.
> Fix add_variable

- TM1py/Services/CellService.py
- TM1py/Utils/Utils.py
removed inconsistency in returned dictionary between normal MDX queries
and MDX queries with calculated members
> Fix execute_mdx WITH MEMBER inconsistency

- TM1py/Utils/Utils.py
Reverts cubewise-code/TM1py#60
> Revert "Build content from cellset"

- TM1py/Services/ProcessService.py
- Tests/Process.py
https://github.com/cubewise-code/TM1py/issues/65
- New function: `execute_with_return` in ProcessService to execute TI processes through the new ExecuteWithReturn Action.
- New function: `get_error_log_file_content` to get the content of error-log-files (e.g. TM1ProcessError_20180926213819_65708356_979b248b-232e622c6.log)
> WIP: execute_with_return and get_error_log_file_content functions

- TM1py/Objects/Dimension.py
- TM1py/Objects/Hierarchy.py
- Tests/Dimension.py
Now when the `name `property of a dimension is updated, TM1py implicitly updates:
- the `dimension_name` property of all hierarchies in the dimension
- the name of the default hierarchy (hierarchy with the same name as the dimension)
> Update dimension name

- TM1py/Services/HierarchyService.py
- Tests/Hierarchy.py
- get_default_member
- update_default_member
> Two new methods in HierarchyService. Fixes #95

- TM1py/Services/SecurityService.py
- TM1py/Services/TM1Service.py
- Tests/Security.py
New `get_current_user `method in `SecurityService`
> New whoami property on TM1Service. Fixes issue #106

- TM1py/Services/RESTService.py
new argument in TM1Service constructor: `connection_pool_size`
allow for a custom sized http connection pool
required when using TM1py in a multithreaded environment
> Make http connection pool size dynamic

- TM1py/Services/RESTService.py
required for check.py from tm1py-samples repository
> Accept int as ssl parameter in TM1Service

- README.md
- setup.py
Changed README.rst to README.md and adjusted dependency in setup.py
> change README file to markdown

- TM1py/Services/ChoreService.py
Hi Marius,
I've realised that the chore update function is not working properly in case the source and destination chore has different number of tasks inside (if there were less, new tasks were not added just caused a TM1 rest error, in case there were more the unnecessary ones were not deleted). Following your logic, I've enhanced the code to make sure that different chore contents are fully synchronised during the update.
Regards,
Adam
> Fixed ChoreService chore update function

- TM1py/Objects/Chore.py
- TM1py/Services/ChoreService.py
- Tests/Chore.py
- Test chore updates that add / remove tasks
- Create static constants for SingleCommit, MultipleCommit
- pep-8 compliance in Chore class
> Add tests for bugs fixed with #133

- TM1py/Services/CellService.py
`execute_view_dataframe`, `execute_mdx_dataframe` methods now expose all arguments
from the `pandas.read_csv` method (e.g. `dtypes`, `parse_dates`)
More details on the arguments here:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html
Fixes #143
> New arguments in execute_*_dataframe methods

- TM1py/Services/RESTService.py
> Check properly if HttpNegotiateAuth exists

- TM1py/Services/CellService.py
- TM1py/Services/ElementService.py
- TM1py/Services/RESTService.py
- TM1py/Utils/Utils.py
- Tests/Cell.py
- Tests/Element.py
- Tests/Utils.py
New methods in `ElementService`, to retrieve all element names and aliases in the hierarchy. 
``` python
def get_all_element_identifiers(self, dimension_name, hierarchy_name):
def get_all_leaf_element_identifiers(self, dimension_name, hierarchy_name):
def get_element_identifiers(self, dimension_name, hierarchy_name, elements):
```
Methods are useful when doing pre checks (if elements exist) before writing to a cube.
> WIP: Feature/get element identifiers

- TM1py/Services/CubeService.py
> Add get_last_data_update method to CubeService

- TM1py/Services/CubeService.py
- Tests/Cube.py
> Add load and unload methods to CubeService

- TM1py/Services/ElementService.py
- Tests/Element.py
- `get_number_of_elements`
- `get_number_of_consolidated_elements`
- `get_number_of_leaf_elements`
> New methods in ElementService

- TM1py/Services/DimensionService.py
- TM1py/Services/ElementService.py
I put this in the element service, but I could see it working in the dim or hierarchy service. Let me know if I should move it.
> Function to execute dimensional mdx queries

- Tests/Annotation.py
- Tests/Application.py
- Tests/Cell.py
- Tests/Chore.py
- Tests/Cube.py
- Tests/Dimension.py
- Tests/Element.py
- Tests/Hierarchy.py
- Tests/Other.py
- Tests/Process.py
- Tests/Security.py
- Tests/Server.py
- Tests/Subset.py
- Tests/TM1pyDict.py
- Tests/Utils.py
- Tests/View.py
Hi 
Thanks for tm1py. I've been doing a bit of cross-platform testing and found a couple of little fixes to how paths are managed. Let me know what you think.
I'm still getting a few failures when running on 3.7.x on windows and Linux but think they're mostly down to issues with the server I'm testing against. I might try to refactor the tests a bit as I go.
Cheers
Alex
> A couple of small fixes for tests

- TM1py/Services/ProcessService.py
- Tests/Process.py
New TI methods to support running unbound TI definitions. Allows for TM1Py process objects to be executed and compiled without being saved.
> Feature run ti code updates

- TM1py/Objects/Dimension.py
- TM1py/Services/DimensionService.py
Leaves Hierarchy is maintained implicitly by TM1 and must not be created or
updated
> Construct Dimension body without Leaves hierarchy

- TM1py/Objects/User.py
- TM1py/Services/SecurityService.py
- Tests/Security.py
New properties in `User` class: `user_type`, `enabled`
> add enabled and usertype property to User

- TM1py/Exceptions/Exceptions.py
- TM1py/Exceptions/__init__.py
- TM1py/Services/CellService.py
- TM1py/Services/DimensionService.py
- TM1py/Services/ObjectService.py
- TM1py/Services/ProcessService.py
- TM1py/Services/RestService.py
- TM1py/Services/ViewService.py
- TM1py/Utils/Utils.py
- Tests/Cell.py
- Tests/Hierarchy.py
- Tests/Other.py
- Tests/Server.py
Add `clear_with_mdx` method to CellService
``` python
with TM1Service(address=ADDRESS, port=PORT, user=USER, password=PWD, ssl=SSL) as tm1:
mdx = """
SELECT
{Tm1SubsetAll([Dimension])} ON 0,
{[CubeMeasure].[Measure]} ON 1
FROM [Cube]
WHERE ([Period].[202003])
"""
tm1.cells.clear_with_mdx(cube="Cube", mdx=mdx)
```
> Add clear_with_mdx method to CellService

- TM1py/Services/CubeService.py
Cube dimension re-order can now return the percent change in memory footprint.
> Get the Percent change in memory

- TM1py/Objects/ChoreStartTime.py
- TM1py/Services/ChoreService.py
- TM1py/Services/CubeService.py
- TM1py/Services/PowerBiService.py
- TM1py/Utils/Utils.py
- Tests/Chore.py
- fix warnings on collections imports
> Fix issue in dst chore time

- TM1py/Utils/MDXUtils.py
- Tests/Cell.py
- setup.py
- add `mdxpy` as a dependency
- use `mdxpy` in `CellService` tests
> Add deprecated warning to MdxUtils

- TM1py/Objects/Element.py
- TM1py/Objects/ElementAttribute.py
- Tests/Element.py
Make ElementAttribute constructor more robust: now accepts type of
attribute in any case
Fixes #244
> Introduce enum for ElementAttribute types

- TM1py/Services/MonitoringService.py
- Tests/MonitoringService.py
Add `cancel_all_threads` and `disconnect_all_users` functions to `MonitoringService`
> Features to replace tm1kill

- TM1py/Services/CubeService.py
- TM1py/Services/DimensionService.py
- TM1py/Services/SubsetService.py
- TM1py/Services/ViewService.py
minor refactoring to other update_or_create methods to use **kwargs (for
timeout etc.)
Fixes #263
> Add update_or_create method to ViewService

- TM1py/Services/SubsetService.py
- Tests/Subset.py
Accommodating https://github.com/cubewise-code/tm1py/issues/262#issue-648862842
> method to covert static subset to dynamic subset

- TM1py/Services/SubsetService.py
> Fix missing comma in update_or_create method

- TM1py/Services/ServerService.py
allows filtering log when log time is not UTC
> Only apply UTC time if not tz info provided

- TM1py/Services/CubeService.py
- Tests/Cube.py
now behaves in line with compile function from ProcessService
Fixes #277
> Refactor check_rules function in CubeService

- TM1py/Services/ServerService.py
- Tests/Server.py
for https://github.com/cubewise-code/tm1py/issues/280#issue-656164989
> 'until' method for get_transaction_log_entries

- TM1py/Services/RestService.py
resolving https://github.com/cubewise-code/tm1py/issues/285#issue-658043988
> Encode '%' just like ' ' and '#'

- TM1py/Exceptions/Exceptions.py
- TM1py/Services/CellService.py
- TM1py/Utils/Utils.py
- Tests/Cell.py
- Tests/Utils.py
> Add `require` decorator to raise version exception

- TM1py/Services/RestService.py
New `integrated_login` argument to `TM1Service` / `RestService` allows login with IntegratedSecurityMode3:
``` python
with TM1Service(address="localhost", port=12354, ssl=True, integrated_login=True) as tm1:
print(tm1.server.get_product_version())
```
> Support IntegratedSecurityMode2 and 3

- Tests/Annotation.py
- Tests/Application.py
- Tests/Cell.py
- Tests/Chore.py
- Tests/Cube.py
- Tests/Dimension.py
- Tests/Element.py
- Tests/Hierarchy.py
- Tests/MonitoringService.py
- Tests/Other.py
- Tests/PowerBiService.py
- Tests/Process.py
- Tests/RestService.py
- Tests/Security.py
- Tests/Server.py
- Tests/Subset.py
- Tests/TM1pyDict.py
- Tests/Utils.py
- Tests/View.py
<s>Omits a couple of test files where the current code is a bit more complicated.</s>
> Align how tm1 connection created in most tests

- TM1py/Services/ElementService.py
- Tests/Element.py
```PYTHON
tm1 = TM1Service()
print(tm1.elements.get_elements_by_wildcard('Month', 'Month', 'qtr'))
```
**Output**: `['Qtr-01', 'Qtr-02', 'Qtr-01', 'Qtr-04']`
```PYTHON
tm1 = TM1Service()
print(tm1.elements.get_elements_by_wildcard('Month', 'Month', 'ju', 0))
```
**Output**: `['June', 'July']`
> get_elements_by_wildcard

- TM1py/Services/HierarchyService.py
- Tests/Hierarchy.py
Solution to https://github.com/cubewise-code/tm1py/issues/322#issue-675997568
Any ideas on refactoring?
> remove_edges_under_consolidation

- TM1py/Utils/TIObfuscator.py
This averts another deprecation warning regex, same change as before.
> Tweak another regex

- Tests/PowerBiService.py
These tests should be skipped too when pandas not installed
> skip more tests when pandas not installed

- Tests/Cell.py
I think changes in https://github.com/cubewise-code/tm1py/pull/325 need the tests to be re-worked as some are now failing for me. I've made a few changes to get them working again. I think they need a bit more a closer look but maybe this will do in the meantime? 
> Change tests to expect list, not generator

- TM1py/Services/ChoreService.py
- Tests/Cell.py
- use `deactivate_activate` decorator on `set_local_start_time` function
- adjust decorator to accept chore or chore_name as arguments
- fix issues in execute_..._values tests
relatd to #301
> Fix deactivate_activate decorator and cell tests

- Tests/Application.py
- Tests/Cell.py
- Tests/__init__.py
A clean up of https://github.com/cubewise-code/tm1py/pull/333
I restored the imports but noticed that not all test files were being imported so added the missing ones.
> Change test class names 

- TM1py/Services/ElementService.py
> Make get_attribute_of_elements work with numeric

- TM1py/Services/MonitoringService.py
- Tests/MonitoringService.py
add new arguments `include_user`, `include_threads`
related to #340
> Parametrize get_sessions method

- TM1py/Services/CellService.py
- TM1py/Utils/Utils.py
- Tests/Cell.py
- Tests/Utils.py
Add transaction_log_is_active function
Fixes #343
> wip: Add manage_transaction_log decorator

- TM1py/Objects/Hierarchy.py
- Tests/Hierarchy.py
add `remove_all_elements` function
add `remove_all_edges` function
> Add remove_all methods to hierarchy class

- Tests/Dimension.py
Hi
A bit of a cleanup of the dimension tests
* move globals to class properties
* add missing assert statement
Cheers
Alex
> Cleaned up dimension tests

- Tests/Element.py
Hi
A bit of a cleanup of the element tests:
* move globals to class
* remove unused function
* re-structured fixtures to ensure idempotency 
Cheers
Alex
> Cleaned up element tests

- Tests/Cube.py
Hi
A small clean up of the cube tests:
* Move globals to class
Cheers
Alex
> cleaned up cube tests

- TM1py/Services/RestService.py
Accept `integrated_login_domain`, `integrated_login_service`,
`integrated_login_host`, `integrated_login_delegate` as arguments in
`TM1Service`, `RestService` and pass them through to `HTTPNegotiateAuth`
Fixes #387
> Accept additional integrate_login arguments

- TM1py/Services/SecurityService.py
- TM1py/Utils/Utils.py
- Tests/Security.py
Add `get_read_only_users` function to SecurityService
Add `get_custom_security_groups` function to SecurityService
Solves #393
> Functions to get read-only-users and custom-groups

- TM1py/Services/CubeService.py
- TM1py/Services/ProcessService.py
- TM1py/Utils/Utils.py
- Tests/Cube.py
- Tests/Process.py
- Tests/Utils.py
1. Add new methods to figure out cubes with rules in `CubeService`
2. Added a new `update or create` method in `ProcessService`
3. Arranged the `create` and `update` methods in `ProcessService`
4. Incorporating #398 .. can't figure out a better way to test
> new updates

- README.md
- setup.py
> Adjust python dependency to 3.8

- TM1py/Objects/MDXView.py
- TM1py/Objects/NativeView.py
- TM1py/Objects/View.py
- Tests/NativeView.py
- Tests/ViewService.py
- Tests/__init__.py
> Build mdx from native view with mdxpy

- TM1py/Services/SecurityService.py
- Tests/Security.py
- Tests/__init__.py
> Add update_user_password to SecurityService

- TM1py/Utils/Utils.py
- Tests/Cell.py
> Fix single axis selection issue in execute_mdx

- TM1py/Services/CellService.py
- TM1py/Utils/Utils.py
- Tests/Cell.py
code to test:
```python
tm1 = TM1Service()
mdx = """
SELECT NON EMPTY
{TM1SUBSETALL( [}Clients] )} * {TM1SUBSETALL( [}Groups] )}
ON 0
FROM [}ClientGroups]"""
csv = tm1.cubes.cells.execute_mdx_csv(mdx)
print(csv)
```
> support row_axis_only MDX queries

- TM1py/Objects/Hierarchy.py
- Tests/Hierarchy.py
- Tests/__init__.py
Add `add_component` function
Fixes #433
> Add add_component function to Hierarchy class

- TM1py/Objects/ChoreStartTime.py
- Tests/ChoreStartTime.py
Fixes https://github.com/cubewise-code/tm1py-samples/issues/82
> Fix chore reschedule issue

- TM1py/Services/CellService.py
- Tests/CellService.py
> Reduce number of characters in string digits

- TM1py/Services/CellService.py
- Tests/CellService.py
> Add include_hierarchies arg to execute_mdx_raw

- TM1py/Services/ServerService.py
- Tests/ServerService.py
> Fix issue in get_audit_log_entries

- TM1py/Objects/Git.py
- TM1py/Objects/GitCommit.py
- TM1py/Objects/GitPlan.py
- TM1py/Objects/GitRemote.py
- TM1py/Services/GitService.py
Minor adjustments to `GitService` and Git related objects
> Adjustments on git functionality

- TM1py/Services/PowerBiService.py
> Align levels on right (level000) in dataframe

- TM1py/Services/CellService.py
- TM1py/Utils/Utils.py
- Tests/CellService.py
- Tests/TestUtils.py
use `display_attribute=True` and user PROPERTIES in MDX query
Related to #470
> Support MDX PROPERTIES in execute_mdx_dataframe

- TM1py/Services/RestService.py
> Accept None for user argument in RestService

- TM1py/Services/ProcessService.py
Add simple debug step-over functionality to allow stepping through a process
> Support process debugging

- TM1py/Services/TM1Service.py
- TM1py/Services/__init__.py
- TM1py/__init__.py
I noticed that the Git service was not available on the context menu.  I added the service to TM1Service.py and __init__.py under Services and TM1Py
> Added GitService to TM1Service and __init__ files

- TM1py/Services/CellService.py
- Tests/CellService.py
Hi, @MariusWirtz 
Finally, got some time to tidy this up. I have done some testing. Please review and test it again.
Happy to discuss further. Have a nice weekend! :)
> Add write_dataframe_async function and tests

- TM1py/Services/ElementService.py
Replace REST call with set MDX to mitigate special characters in attribute names.
> Utilise MDX for attribute filter

- TM1py/Services/HierarchyService.py
New update_or_create method on HierarchyService.
> Update or create hierarchy

- TM1py/Services/CellService.py
in `write_through_unbound_process` function
> Explicitly convert value to str for str measure

- TM1py/Services/CellService.py
- Tests/CellService_test.py
introduce new `write_async` function
> Improve `write_dataframe_async` function

- TM1py/Utils/Utils.py
Resolves #583 
Signed-off-by: Felipe Fonseca <ffonseca@cubewise.com>
> get_all_servers_from_adminhost: added parameters for PORT and SSL

- TM1py/Services/ProcessService.py
Hi @MariusWirtz 
as discussed on #588 adding the named arguments.
> add explicit arguments

- TM1py/Services/RestService.py
inspired by https://github.com/cubewise-code/tm1py/pull/607#issuecomment-924915039
> Allow login with cam_passport

- TM1py/Services/CellService.py
Cater for rare error that cellset is already removed from the server
> Dont fail delete_cellset if cellset is removed

- TM1py/Services/ElementService.py
- Tests/ElementService_test.py
- remove spaces from attribute names
- improve docstring
- add tests
Fixes #648
> Improve execute_set_mdx function

- TM1py/Services/ChoreService.py
- Tests/ChoreService_test.py
- Tests/__init__.py
- Tests/_readme.md
- cater for numeric parameter values
- add readme for tests
- fix all chore tests
successor of #663
> Minor improvements on chore search

- TM1py/Services/HierarchyService.py
- Tests/HierarchyService_test.py
> Support attribute type changes

- TM1py/Services/CellService.py
- Tests/CellService_test.py
> Allow `skip_zeros` in `execute_mdx_values`

- TM1py/Services/CellService.py
Add new parameters to `write_dataframe` function
> Align write_dataframe function with write function

- TM1py/Objects/MDXView.py
- TM1py/Objects/NativeView.py
- Tests/MDXView_test.py
- Tests/NativeView_test.py
New function allows to substitute selection in MDX WHERE part in a friendly way.
> Add `substitute_title` function to `MDXView`

- TM1py/Services/CellService.py
Make use of built-in csv module.
Fixes #696
> Fix doubled double quotes in response

- TM1py/Services/DimensionService.py
On dimension update explicitly add elements to leaves hierarchy
that are not included in any other hierarchy.
Fixes #702
> Explicitly add elements to leaves hierarchy

- TM1py/Services/CellService.py
> Retrieve ordinal for iterative json parsing

- TM1py/Services/CellService.py
> Split hierarchy and element name with maxsplit=1

- TM1py/Services/CubeService.py
- TM1py/Services/DimensionService.py
- TM1py/Services/ProcessService.py
- Tests/CubeService_test.py
- Tests/NativeView_test.py
- Tests/ProcessService_test.py
@adscheevel
I made a few small changes. Please review and approve.
> Minor changes and adjustments

- TM1py/Services/CellService.py
- Tests/CellService_test.py
New methods for calculation tracing.
> Added support for trace calculations, trace feeders, and check feeders

- Tests/CellService_test.py
@rclapp please review and approve.
I included a test for the depth of the response.
> Test depth in trace calc tests

- TM1py/Services/ProcessService.py
- Tests/ProcessService_test.py
> Add debugging tests

- TM1py/Objects/Process.py
- TM1py/Services/CellService.py
- Tests/CellService_test.py
> Use 100k max statements in write use_ti

- Tests/NativeView_test.py
Align tests with mdxpy 1.0 release
> Fix tests for native view

- TM1py/Services/CellService.py
- TM1py/Utils/Utils.py
Add argument skip_sandbox_dimension to execute_mdx function for #789
> Add argument skip_sandbox_dimension to execute_mdx 

- TM1py/Services/HierarchyService.py
> Create element attributes when creating hierarchy

- .gitignore
https://github.com/github/gitignore/blob/main/Python.gitignore
Fixes #847
> Use standard gitignore

- TM1py/Services/ElementService.py
> Attempt to import pandas in ElementService

- TM1py/Services/ElementService.py
> Fix wrong usage of format_url function

- TM1py/Services/RestService.py
Fix of https://github.com/cubewise-code/tm1py/pull/856
> Don't attempt re_connect at first connection

- TM1py/Services/SandboxService.py
- Tests/ChoreService_test.py
- Tests/ElementService_test.py
- Tests/SandboxService_test.py
- Tests/Sandbox_test.py
- Tests/SecurityService_test.py
Fix tests for TM1 11.8.01900.10
> Fix broken tests

- TM1py/Utils/Utils.py
> Encode ampersand in object names for URL

- TM1py/Services/RestService.py
Impement function to create urllib3.HTTPResponse
based off bytes string from async_requests_mode response
Fixes #917
Fixes #914
> Cater to breaking in change in urllib3 2.0 release

- Tests/CellService_test.py
- Tests/config.ini
Small correction to test case to fix element order.
> Update test case to correct element order in assert

- TM1py/Services/CellService.py
- Tests/CellService_test.py
New method for executing multiple MDX queries in parallel and combine the results into one dataframe. Can be used to speed up MDX queries by splitting MDX into smaller MDX subqueries. This may be one of the approaches to the issue https://github.com/cubewise-code/tm1py/issues/887
> Asynchronous  execute_mdx_dataframe was added

- TM1py/Services/ElementService.py
- Tests/ElementService_test.py
> Delete multiple elements using TI

- TM1py/Objects/Chore.py
- TM1py/Objects/ChoreTask.py
- Tests/Chore_test.py
Cater to differences between GET and POST JSON
> Make JSON parsing for Chore robust

- TM1py/Objects/NativeView.py
- TM1py/Objects/Subset.py
- TM1py/Utils/Utils.py
- Tests/NativeView_test.py
- Tests/config.ini
Cater to differences between GET and POST JSON
> Make JSON parsing for NativeView robust

- TM1py/Services/CellService.py
> Remove temp view in `_execute_view_csv_use_blob`

- TM1py/Services/CellService.py
To enable single commit of clearing and writing to cube.
> Added clear view argument to write_through_blob

- TM1py/Services/CellService.py
- TM1py/Utils/Utils.py
- Tests/CellService_test.py
> Add `arranged_axes` arg to execute_view_csv functions

- TM1py/Services/HierarchyService.py
- Tests/CellService_test.py
> Allow nan values in level columns

- TM1py/Services/HierarchyService.py
- Tests/HierarchyService_test.py
default weight is 1 when no weight columns are provided
> weight columns as optional in hierarchy df

- setup.py
Make sure master branch version is > pypi version
> Upgrade setup.py file for 1.12

- TM1py/Services/ElementService.py
Also check for None explicitly in
- `get_elements_dataframe`
- `get_attribute_of_elements`
> Use any instead of list for empty checks

- TM1py/Services/ElementService.py
- TM1py/Services/HierarchyService.py
Weight columns are now aligned with parent columns Weights on edges now get update on element dataframe write function
> Fix element dataframe functions

- TM1py/Services/HierarchyService.py
- Tests/HierarchyService_test.py
> Fix issues in update_or_create_hierarchy_from_df

- TM1py/Objects/Hierarchy.py
- Tests/Hierarchy_test.py
> Add replace_element function to Hierarchy class

- TM1py/Services/ElementService.py
added update_or_create function in ElementService.py
> added update_or_create function in ElementService.py

- TM1py/Services/ElementService.py
- Tests/ElementService_test.py
> Add allow_empty_alias argument to get_elements_df

- TM1py/Services/CellService.py
- TM1py/Utils/Utils.py
Remove obsolete and unexpected records in shaped df response on execute_view, execute_mdx functions
> Fix issue 997

- TM1py/Services/FileService.py
- Tests/FileService_test.py
> File service 202401

- TM1py/Services/MessageLogService.py
- TM1py/Services/ServerService.py
fixes issue https://github.com/cubewise-code/tm1py/issues/1051
> utc_localize_time move from to MessageLog Service

- TM1py/Services/RestService.py
> Assure backwards compatability with api/v1 urls

- TM1py/Services/ElementService.py
Read first column as string in element attribute df
> Fix issue in `get_elements_dataframe` w `use_blob`

- TM1py/Services/ElementService.py
> Make numpy import optional in ElementService

- TM1py/Services/RestService.py
- TM1py/Services/TM1Service.py
Added support for PA Proxy on CP4D for UN/PW connections
Improved logut behaviors by not raising exceptions when logout fails when invoked from a context manager  __exit__
> Support for PA Proxy on CP4D and Improved Logout Behaviors

- TM1py/Services/ElementService.py
- Tests/ElementService_test.py
in get_elements_dataframe function
Fix #1083
> Assure use_blob doesn't impact result

- TM1py/Services/RestService.py
> Fix _determine_auth_mode for WIA

- Tests/AnnotationService_test.py
Finally, there was a small error in the annotation test :-/ Sorry.
Name Error in f3317d0b619f42599208d37b36b1a7d726a3f0e2
> Fix: NameError introduced in last refactoring

- TM1py/Services/FileService.py
- Tests/FileService_test.py
> Allow IO of files to subfolders in v12

- TM1py/Services/CellService.py
Now properly escape double quotes in elements and values when using csv blob exchange in execute_mdx_csv, execute_mdx_dataframe
Solves #1110
> Support double quotes in execute_mdx_csv

- TM1py/Services/ProcessService.py
A small def summary for ProcessService.py
> Small adjustment to the summary of a def

- TM1py/Services/HierarchyService.py
- Tests/HierarchyService_test.py
in update_or_create_hierarchy function
Fixes #1139
> Optional update attribute type feature

- Tests/DimensionService_test.py
Just simplify a test in `DimensionService_test`
> Refactor: Simplify exception test

- .github/workflows/unit_test_pipeline.yml
- setup.py
Added functionality to test on demand per PR request. For security reasons, we cannot automate this process as it could expose our environment secrets.
> Ci pipeline pr testing

- TM1py/Services/RestService.py
> Add new auth mode: access_token for v12 in AKS

- TM1py/Services/CubeService.py
Browsing through the TM1py source code, I noticed another small improvement...
The test coverage here is pretty good, so I'm convinced that everything should work as before.
> Refactor: Simplify parameter validation

- README.md
Add access-token auth mode in readme
> Drop MCSP from readme

- TM1py/Utils/Utils.py
- Tests/CellService_test.py
Fix #1181 write_dataframe to be case and space insensitive loading to same intersection.
> Fix #1181 write_dataframe case and space insensitive

- Tests/HierarchyService_test.py
test case for case and space insensitive unwind consolidation
closes #1174
> Test case for 1174

- TM1py/Services/RestService.py
- TM1py/Services/TM1Service.py
Update TM1Service and RestService to support users utilizing MTLS connections.
> Support paas MTLS certs to RestService

- TM1py/Services/HierarchyService.py
- Tests/HierarchyService_test.py
in update_or_create_hierarchy_from_dataframe function
solves #1211
> Make level columns case insensitive

- TM1py/Services/RestService.py
added keyword parameter to RestService.request to make the verify response function optionally ignored
> Make Verify Response Optional
